name: egot_services
version: 1.0.0+1
publish_to: none
description: Egot eco system projet pilote.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.5
  get: ^4.6.5
  firebase_storage: any
  animated_text_kit: ^4.2.2
  flutter_signin_button: 2.0.0
  ar_flutter_plugin: ^0.7.3
  flutter_launcher_icons: ^0.11.0
  google_maps_flutter: ^2.2.2
  location: ^4.4.0
  get_storage: 2.0.3
  snapping_page_scroll: 2.1.0
  web_socket_channel: ^2.2.0
  firebase_app_check: ^0.1.1+8
  firebase_core: ^2.4.1
  firebase_auth: any
  firebase_ui_firestore: any
  cloud_firestore: ^4.3.1
  envied: 0.3.0
  shared_preferences: 2.0.15
  connectycube_sdk: 2.2.3
  connectivity_plus: 3.0.2
  file_picker: 5.2.4
  geoflutterfire: 3.0.3
  geolocator: 9.0.2
  firebase_analytics: 10.1.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  build_runner: 2.3.3
  envied_generator: 0.3.0
  flutter_test: 
    sdk: flutter

dependency_overrides: 
  cloud_firestore: ^4.3.1

flutter_icons: 
  image_path: assets/lottie/image/godzy_logo.png
  android: true
  ios: true

flutter: 
  assets: 
    - assets/lottie/image/carrelage_background.jpg
    - assets/lottie/image/godzy_logo.png
    - assets/lottie/image/logo_bat_services.png
    - assets/lottie/image/digital-transformation-teaser.jpg
    - assets/lottie/image/digital_transf.jpg
    - assets/lottie/image/maison_indiv.png
    - assets/lottie/image/appartement.png
    - assets/lottie/image/triangle.png
    - assets/lottie/archive/amenagement/interrieur/sol/matière/pvc/sol_pvc_holywell.png
    - assets/lottie/archive/amenagement/exterieur/piscines/piscine_sussargue_1.jpg
    - assets/lottie/models/Android Robot.gif
    - assets/lottie/models/AndroidRobot.gif
    - assets/lottie/models/Arctic Fox (Sitting).gif
    - assets/lottie/models/ArcticFox.gif
    - assets/lottie/models/Toco Toucan.gif
    - assets/lottie/models/TocoToucan.gif
    - assets/lottie/models/fox_face_mesh_texture.png
    - assets/lottie/models/prova_texture.png
    - assets/lottie/models/venom.jpg
    - assets/lottie/models/venom_with_eyes.jpg
    - assets/lottie/models/earth.jpg
    - assets/lottie/models/earth (2).jpg
    - assets/lottie/models/earth_augmented_image.jpg
    - assets/lottie/models/copertina.jpg
    - assets/lottie/models/umano_digitale.png
    - assets/lottie/models/myimages.imgdb
    - assets/lottie/models/topolino.jpg
    - assets/lottie/models/santa_maria_madalena/
    - assets/lottie/models/
    - assets/.env
  uses-material-design: true

