name: egot_services
version: 1.0.0+1
publish_to: none
description: Egot eco system projet pilote.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.3
  get: ^4.3.0
  getxfire: ^0.1.9
  firebase_storage: any
  google_sign_in: any
  animated_text_kit: 4.2.1
  flutter_signin_button: 2.0.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.4
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/lottie/image/carrelage_background.jpg
    - assets/lottie/image/godzy_logo.png
    - assets/lottie/image/logo_bat_services.png
    - assets/lottie/image/digital-transformation-teaser.jpg
    - assets/lottie/image/digital_transf.jpg
    - assets/lottie/archive/amenagement/interrieur/sol/matière/pvc/sol_pvc_holywell.png
    - assets/lottie/archive/amenagement/exterieur/piscines/piscine_sussargue_1.jpg
  uses-material-design: true

