name: egot_services
version: 1.0.0+1
publish_to: none
description: Egot eco system projet pilote.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.4
  get: ^4.6.1
  getxfire: ^0.3.3
  firebase_storage: any
  animated_text_kit: 4.2.1
  flutter_signin_button: 2.0.0
  ar_flutter_plugin: ^0.6.2
  geoflutterfire: ^3.0.2
  flutter_launcher_icons: ^0.9.2
  google_maps_flutter: ^2.1.1
  location: 4.3.0
  get_storage: 2.0.3
  snapping_page_scroll: 2.1.0
  flutter:
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.4
  flutter_test: 
    sdk: flutter

flutter_icons: 
  image_path: assets/lottie/image/godzy_logo.png
  android: true
  ios: true

flutter: 
  assets: 
    - assets/lottie/image/carrelage_background.jpg
    - assets/lottie/image/godzy_logo.png
    - assets/lottie/image/logo_bat_services.png
    - assets/lottie/image/digital-transformation-teaser.jpg
    - assets/lottie/image/digital_transf.jpg
    - assets/lottie/image/maison_indiv.png
    - assets/lottie/image/appartement.png
    - assets/lottie/image/triangle.png
    - assets/lottie/archive/amenagement/interrieur/sol/matière/pvc/sol_pvc_holywell.png
    - assets/lottie/archive/amenagement/exterieur/piscines/piscine_sussargue_1.jpg
    - assets/lottie/models/Android Robot.gif
    - assets/lottie/models/AndroidRobot.gif
    - assets/lottie/models/Arctic Fox (Sitting).gif
    - assets/lottie/models/ArcticFox.gif
    - assets/lottie/models/Toco Toucan.gif
    - assets/lottie/models/TocoToucan.gif
    - assets/lottie/models/fox_face_mesh_texture.png
    - assets/lottie/models/prova_texture.png
    - assets/lottie/models/venom.jpg
    - assets/lottie/models/venom_with_eyes.jpg
    - assets/lottie/models/earth.jpg
    - assets/lottie/models/earth (2).jpg
    - assets/lottie/models/earth_augmented_image.jpg
    - assets/lottie/models/copertina.jpg
    - assets/lottie/models/umano_digitale.png
    - assets/lottie/models/myimages.imgdb
    - assets/lottie/models/topolino.jpg
    - assets/lottie/models/santa_maria_madalena/
    - assets/lottie/models/
  uses-material-design: true

